name: zebra
description: A Finch app goal viewer

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1
  flutter: 3.22.0

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  file_picker: ^8.0.3
  fluttertoast: ^8.2.6
  flutter_heatmap_calendar: ^1.0.5
  archive: ^3.6.1
  json_annotation: ^4.9.0
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_native_select: ^1.0.1
  go_router: ^14.2.7
  url_launcher: ^6.3.0
  url_strategy: ^0.3.0
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  hive_test: ^1.0.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true