name: Analyze workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ "master" ]
    types: [review_requested, ready_for_review]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
        - name: Clone repository
          uses: actions/checkout@v4
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            flutter-version-file: pubspec.yaml # path to pubspec.yaml
        - run: flutter --version
        - run: flutter config --no-analytics # we do not want analytics
        - run: flutter config --no-cli-animations # no need for animations in CI
        - name: Analyze
          run: flutter analyze
        - name: No diff
          run: git diff --exit-code
